# jekyll-docs-template specific variables
title: 'Jekyll Docs Template'
subtitle: 'Painless documentation using Jekyll'
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

baseurl: '/jekyll-docs-template/'

pygments: true
future: false

markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
